# Generated by Django 2.2.6 on 2019-11-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191118_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
