# Generated by Django 2.2.6 on 2019-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
